package cli

// End-to-end tests for `flow invoke` in a project-scoped context.
// Reproduces: task creation fails with "failed to get project_id: sql: no rows"
// when invoked from a directory that has a project.id in .tlc/config.yaml
// and DetectProject() returns InProject=true.

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"
)

// TestFlowInvoke_ProjectScoped_CreatesTasksWithoutError reproduces the bug
// where `flow invoke` fails with:
//
//	failed to create task T-<uuid>: failed to create task:
//	failed to add log: failed to get project_id: sql: no rows in result set
//
// when run from a project-scoped directory (project.id set in .tlc/config.yaml).
//
// Root cause: ExtractTasksFromFlow / flow executor creates tasks without setting
// task.ProjectID, so the task is stored with project_id=”. AddLog then queries
// tasks filtered by DetectProject().ProjectID (e.g. "test/project") — finding
// no row — and returns sql.ErrNoRows.
func TestFlowInvoke_ProjectScoped_CreatesTasksWithoutError(t *testing.T) {
	withTestLock(func() {
		tmpDir, _ := setupProjectScopedTestDir(t, "tlc-flow-invoke-project-", "test/project")

		// Write a minimal flow yaml with one task template.
		flowPath := filepath.Join(tmpDir, "test-flow.yaml")
		flowYAML := `flow_id: "flow:test:1.0"
name: "Test Flow"
version: "1.0"
entry_step: "step-one"
steps:
  step-one:
    step_id: "step-one"
    type: "task"
    title: "Step One"
    task_template:
      title: "Do the thing"
      description: "A test task generated by flow invoke"
`
		if err := os.WriteFile(flowPath, []byte(flowYAML), 0o644); err != nil {
			t.Fatalf("WriteFile flow yaml: %v", err)
		}

		cmd := newTestCmd()
		cmd.AddCommand(FlowCmd)
		buf := new(bytes.Buffer)
		cmd.SetOut(buf)
		cmd.SetErr(buf)
		cmd.SetArgs([]string{"flow", "invoke", flowPath})

		if err := cmd.Execute(); err != nil {
			t.Fatalf("flow invoke in project-scoped dir: %v\noutput:\n%s", err, buf.String())
		}

		out := buf.String()
		if !contains(out, "invoked successfully") {
			t.Errorf("expected success message in output; got:\n%s", out)
		}
	})
}
