name: lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    uses: hop-top/kit/.github/workflows/lint.yml@main
    with:
      version: v2.8.0
    secrets: inherit
